name: RamCTF
version: '1.0-SNAPSHOT'
main: me.ramctf.RamCTF
api-version: 1.20.6
commands:
  setup:
    description: game host setup
    usage: /<command>
  team:
    description: get team menu
    usage: /<command>